<?php
/**
 * Created by PhpStorm.
 * User: Behzod
 * Date: 17.03.2019
 * Time: 17:57
 */

namespace app\components;


use yii\db\ActiveRecord;

class Model extends ActiveRecord
{
    public static function findall()
    {
        return self::find()->all(); // TODO: Change the autogenerated stub
    }

}